apiVersion: v1/beta
kind: Deployment
metadata: 
  name: Devops
 spec:
  labels:
    fruit: apple
    color: red
  templates:
    name: node js:0.4
    labels:
      fruit: apple
      color: red
      need to practice 
